name: Travis Richardson
favicon: null
layout_spectrum: 0.061787037178874016
typography_spectrum: 0.03150832583196461
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5096600365359336
  lightness: 0.004283952759578824
  saturation: 0.2127904687076807
  rhythmicContrast: 0.1998248496092856
purpose: []
