name: Travis Richardson
favicon: null
layout_spectrum: 0.24586
typography_spectrum: 0.2545
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#faf6f7'
    - '#e3dad3'
    - '#bab4a9'
    - '#865a42'
    - '#a0745f'
  brandStrength: 0.5096600365359336
  lightness: 0.004283952759578824
  saturation: 0.2127904687076807
  rhythmicContrast: 0.1998248496092856
purpose: []
